# Generated by Django 3.1.6 on 2021-02-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagment', '0002_auto_20210128_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockmanagment.category'),
            preserve_default=False,
        ),
    ]
